%% Error function
f = @(origin, pos1, pos2, pos3, pos4) ...
    norm(origin - pos1)^2 ...
    + norm(norm(pos1 - pos2) - DIST(1,2))^2 ...
    + norm(norm(pos1 - pos3) - DIST(1,3))^2 ...
    + norm(norm(pos1 - pos4) - DIST(1,4))^2 ...
    + norm(norm(pos2 - pos3) - DIST(2,3))^2 ...
    + norm(norm(pos2 - pos4) - DIST(2,4))^2 ...
    + norm(norm(pos3 - pos4) - DIST(3,4))^2 ...
    ;

fun = @(X) f([0,0], X(1,:), X(2,:), X(3,:), X(4,:));